### ISSUE TITLE
Wiki support for HTML and CSS

### ISSUE THREAD

**Issue by jtittler** [MicrosoftDocs/vsts-rest-api-specs#100]
I have documentation auto generated by CompuDocs for an Ionic project. This doesn't support Markdown. It's a whole website, not just one or 2 html pages. There are UML diagrams and crosslinked JSDoc stuff. I'd love to be able to just drop in a small website for a wiki. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 245af1b8-7b28-69a8-dde7-25862d749b49
* Version Independent ID: 38be9fbb-5300-0d94-59c4-7e425c2d1a23
* Content: [Wikis (VSTS Wiki)](https://docs.microsoft.com/en-us/rest/api/vsts/wiki/wikis?view=vsts-rest-4.1&viewFallbackFrom=vsts)
* Content Source: [docs-ref-autogen/4.1/wiki/Wikis.yml](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-autogen/4.1/wiki/Wikis.yml)
* Product: **devops**
* GitHub Login: @wnjenkin
* Microsoft Alias: **whjenkin**

**Comment by sandeepchads** [comment]
@jtittler can you please add this requirement to our user voice? https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services?category_id=210055

We already have a user voice on plant UML. PLease feel free to upvote it so that you can get notified once we complete it.

https://visualstudio.uservoice.com/forums/330519-azure-devops-formerly-visual-studio-team-services/suggestions/31210696-wiki-mermaid-plantuml-support

Thanks
Sandeep
