### ISSUE TITLE
OpenApi models generation

### ISSUE THREAD

**Issue by dnws** [MicrosoftDocs/vsts-rest-api-specs#114]
Hello,

I am new to swagger/openapi and trying to generate models based on OpenApi specifications for Azure DevOps, specifically for [build.json ver 5.0](https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/build/5.0/build.json).
I see that version referenced is **"swagger": "2.0"**. But trying to generate models out of this specification leads to different errors depending on swagger version used. 

Latest stable codegen 2.3.1 ignores all the additional properties of object if it has **allOf** in it. 

For example **BuildDefinition** object:

```json
  "BuildDefinition": {
      "description": "Represents a build definition.",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/BuildDefinitionReference"
        }
      ],
      "properties": {
        "badgeEnabled": {
          "description": "Indicates whether badges are enabled for this definition.",
          "type": "boolean"
        },
        "buildNumberFormat": {
          "description": "The build number format.",
          "type": "string"
        },
        "comment": {
          "description": "A save-time comment for the definition.",
          "type": "string"
        },
        "demands": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Demand"
          }
        },
        "description": {
          "description": "The description.",
          "type": "string"
        },
............
```

Generation command:

```
java -jar swagger-codegen-cli.jar generate \
   -i build.json \
   -l csharp \
   -o test \
   -Dmodels
```

It generates class with all the properties of **BuildDefinitionReference**, but not a single "native" property like BuildNumberFormat and so on. 

Am I on wrong version, or missing some arguments? Which tool is best to use to generate models according to these specs?

___
Thankful for any hints/suggestions!

**Comment by kjartab** [comment]
I am having problems generating code as well. Neither swagger-codegen-cli nor autorest are able to produce C# code that actually works. I haven't been able to find documentation regarding use of these swagger definitions. Some help would be greatly appreciated.

**Comment by tedchamb** [comment]
@dnws / @kjartab , the only code generation tooling I am familiar with is autorest.  I do know that some people have had success with it.  The swagger 2.0 files in this repo are used as the only source to generate our [REST API documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.0), and that is their main purpose.  Swagger 2.0 has limitations, and you will see that we have to leverage a number of custom properties to fully describe our APIs.  Generic code generators are not going to know about the custom fields.  All of our Swagger files should match the [Swagger 2.0 specs](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).  If you find any where that is not the case, please let me know.  When choosing a code generator ensure that that generator has full support for Swagger 2.0.

Overall my recommendation is to leverage one of our existing [client libraries](https://docs.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-5.0#client-libraries), rather than generating one yourself.  These client libraries provide a lot of benefits that you will not get from code generated using the swagger as the source.

Thanks,
Ted

**Comment by kjartab** [comment]
@tedchamb Thanks for the quick reply. I have tried the client libraries you refer to and they work great, but as I am trying to use these APIs in an azure function v2 context combined with cosmos db and azure servicebus, it's not really an option. Long story short; functions v2 has to be used, meaning .net core and therefore it doesnt support .net framework dependencies (which, sadly, is needed for a tiny subset of the dependencies of these client librares). Any plans for converting them to .net standard 2.0? I will try a bit more with the generators then.

**Comment by tedchamb** [comment]
@kjartab, all of our preview NuGet packages include NetStandard 2.0 versions of the binaries.

**Comment by kjartab** [comment]
![image](https://user-images.githubusercontent.com/3154173/49765297-51c50c00-fcd2-11e8-9999-92f0302ab037.png)

You will have to excuse my lacking understanding of how .net standard 2.0/core 2.x/framework 4.6.x packages work, but the messages in the image above keep popping up. Microsoft.AspNet.WebApi.Client can be upgraded to 5.2.7 which then is restored to .net standard and the issue is resolved. But Windows.Bcl.Build is stuck on .net framework, so when this is loaded into an azure function v2 (.net core 2), which could be running on linux for that matter - it wont work. As I understand it that is, but I would like it if thats wrong.

**Comment by tedchamb** [comment]
@kjartab , 
Unfortunately we have some dependencies that do not have specific binaries built for NetStandard for either the version we need and in some cases even for the latest version.  The good news is that portable binaries are fully compatible with NetStandard, and they do supply portable versions of their binaries in their NuGet packages.  You just need to add a fallback in your project file, so it knows which one to prefer.

```
  <PropertyGroup>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net451+win8</AssetTargetFallback>
  </PropertyGroup>
```

**Comment by kjartab** [comment]
@tedchamb Now I am a bit confused as it seems to just work now with .net.sdk.functions 1.0.24 og az func v2. In any case: Referencing these client libraries in a .net standard 2.0 project and then using them in an azure function v2 app works fine. Thank you for your help!
