### ISSUE TITLE
Sample urls for commits api documentation are not correct

### ISSUE THREAD

**Issue by pelavall** [MicrosoftDocs/vsts-rest-api-specs#15]
See [here](https://docs.microsoft.com/en-us/rest/api/vsts/git/commits/get%20commits). The sample rest api calls have request urls which are not correct. All the sample urls are: 
'GET https://fabrikam.visualstudio.com/{project}/_apis/git/repositories/278d5cd2-584d-4b63-824a-2ba458937249/commits?api-version=4.1-preview'. Instead of the appropriate url for the given sample.

**Comment by wnjenkin** [comment]
Adding @vtbassmatt  to help out

**Comment by vtbassmatt** [comment]
I've been pushing to have this (and many, many other examples) fixed for months. For VSTS folks, you can watch mseng bug 1180931 to see where it goes.

**Comment by phun-ky** [comment]
@vtbassmatt could you supply a link to that bug?

**Comment by vtbassmatt** [comment]
@phun-ky sure, but only MS employees will be able to see it. https://mseng.visualstudio.com/CSI/_workitems/edit/1180931

**Comment by wnjenkin** [comment]
@pelavall closing this out. The sample url have been update. https://docs.microsoft.com/en-us/rest/api/vsts/git/commits/get%20commits?view=vsts-rest-5.0

**Comment by pelavall** [comment]
@wnjenkin I don't see the correct example urls on the page which you've linked. I also don't 100% understand the resolution for the mseng bug. It doesn't seem to me that it was actually resolved. Reactivating.

**Comment by tedchamb** [comment]
The mseng bug referred to above was for the team that owns the documentation rendering.  They resolved it as it turned out the issue was in the example json rather than an infrastructure issue.  Bug 1268149 is assigned to the team that owns that end point, and covers the Get Commits examples.  It is still active.  If you know of examples on other pages that are incorrect, please let us know, so we can file bugs for them also.

**Comment by pelavall** [comment]
@tedchamb Thanks!
