### ISSUE TITLE
Duplicate `operationId` 

### ISSUE THREAD

**Issue by hbuckle** [MicrosoftDocs/vsts-rest-api-specs#152]
I want to generate a golang client but the swagger validation is failing as many of the definitions have duplicate `operationId` entries. For example in [release.json](https://github.com/MicrosoftDocs/vsts-rest-api-specs/blob/master/specification/release/5.1/release.json)

```
- "List" is defined 4 times
- "Create" is defined 2 times
- "Get" is defined 2 times
- "Update" is defined 4 times
```

**Comment by nschonni** [comment]
I opened #141 to flag some of the issues based off of what the Azure REST specs use. I think they might have a separate checker for the duplicates though

**Comment by tedchamb** [comment]
These swagger files are used to generate our REST documentation, and that is there main purpose.  The `operationId` is used for the title of the method in the docs for example:  [Releases - Create](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases/create?view=azure-devops-rest-5.0)  comes from `<tag> - <operatiodId>`  The non-unique `Create` value is intentional to make the docs simpler and more consistent.

I will follow up with the team that owns the doc generation tooling to see if we can get the same behavior while still keeping the `operationId` unique.

In the meantime you could write a quick script to replace the `operationId` value with the value of its sibling `x-ms-vss-method` property, as this will always be unique.

**Comment by fearthecowboy** [comment]
FYI : , `operationId` is required to be [unique](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#user-content-operationid) in swagger/openapi

**Comment by hbuckle** [comment]
> 
> 
> These swagger files are used to generate our REST documentation, and that is there main purpose. The `operationId` is used for the title of the method in the docs for example: [Releases - Create](https://docs.microsoft.com/en-us/rest/api/azure/devops/release/releases/create?view=azure-devops-rest-5.0) comes from `<tag> - <operatiodId>` The non-unique `Create` value is intentional to make the docs simpler and more consistent.
> 
> I will follow up with the team that owns the doc generation tooling to see if we can get the same behavior while still keeping the `operationId` unique.
> 
> In the meantime you could write a quick script to replace the `operationId` value with the value of its sibling `x-ms-vss-method` property, as this will always be unique.

Fair enough, but the name of the repo implies that these are the API specifications - if they're not it seems like this should be a private repo, otherwise people will keep assuming it contains valid specs.

**Comment by japj** [comment]
> I will follow up with the team that owns the doc generation tooling to see if we can get the same behavior while still keeping the `operationId` unique.

@tedchamb any update you can share on this?

If it is not possible to use the swagger specs from this repo, is there a way to get “clean” specs from the AzureDevOps team somewhere?

**Comment by tedchamb** [comment]
@japj - There is an ongoing discussion with the Azure doc teams to see how we can rectify this issue, while still having our docs render correctly.  I don't have a solution yet or an eta.

In the meantime you could write a quick script to replace the operationId value with the value of its sibling x-ms-vss-method property, as this will always be unique.

**Comment by SirAlvarex** [comment]
I'm also investigating using these swagger docs to replace our internal-handcrafted golang API against AzDO.  I wrote a script to do as you said and replaced the operationId with x-ms-vss-method.  This allows me to generate an example API.

However I found that List operations don't seem to work.  As an example for listing builds:
```
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Build"
              }
            }
          }
```

This expects the return payload to be a []Build.  But the actual return object is { count: int, value: []Build }.  This also exposes itself as incorrect here in the docs: https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-5.0#response

**Comment by tedchamb** [comment]
@SirAlvarex, yes, any REST endpoint that says it returns a list, will actually return a wrapped list, of the type you noted above.

**Comment by japj** [comment]
Ok, I just realized that this list thing is also documented differently from other Azure Rest Api docs.

E.g. see https://docs.microsoft.com/en-us/rest/api/advisor/operations/list?view=azdevserver-2019#response

There the response to a List operation is typically called a List or ListResult (in that case OperationEntityListResult) which then specifies the properties (e.g. value is of type OperationEntity[])

From this whole discussion, I think it is clear enough that the current purpose is to only document the apis. The swagger files in their current form are not intended to generate code with (and it seems we run into multiple issues while trying this). But there seem to be at least some people interested in the code generation aspect.

@tedchamb is there a way that we can help move this forward in a generic way or do we run into issues with the doc generation tools?
I don’t like forking this repo just to “prepare” the swagger files to be code generation ‘ready’.

**Comment by nschonni** [comment]
I opened #201 as a possible way forward

**Comment by japj** [comment]
Looking at https://github.com/Microsoft/azure-devops-python-api it looks like it is possible to generate the python client code with autorest?

**Comment by tedchamb** [comment]
Let me try to summarize our current state.  We have internal tooling that generates all of our REST clients.  It uses code reflection, route registration, language specific settings, and templates as input.  One of the 'languages' we output is Swagger 2.0, which is used for documentation purposes.  We also use this tool to generate c#, [python](https://github.com/Microsoft/azure-devops-python-api), [node](https://github.com/Microsoft/azure-devops-node-api), the [typescript extension sdk](https://github.com/Microsoft/azure-devops-extension-sdk), internal typescript, and previously java.  

This is different than how the Azure organization works.  In my understanding they handcraft their swagger and then code there server side endpoints to match.  

We already had thousands of endpoints before we ever looked into generating swagger.  What we quickly found is that the swagger 2.0 spec is limited and can not fully describe our api.  In order to work around this, we use a lot of custom properties in the swagger that the documentation tooling recognizes.  There are not custom properties for everything, and existing properties also have limitations on what they support.  Therefore there is information loss when converting the input data to our generation tooling into the swagger, which means that any client built from that swagger would not have all the information necessary to build the best client we can.   The custom properties would also mean that we would need to build autorest extensions to handle those.

One thing we would like to do is to build a better Open API spec document for our endpoints that is meant for code generation.  It will not build clients as good as what we can do with our internal generation for the reasons mentioned above, but would be good enough to generate useful clients, and allow consumers to use other Open Api spec tooling.    The only thing holding us back from doing this is priorities.  We only have so much engineering bandwidth, and we have a large number of high priority tasks with a steady stream of more incoming.  The priority of these tasks is always measured in the beneficial impact to our customers.  I am not sure when this particular task would make it to the top of that list.

For those of you on this thread that are Microsoft employees, you can contact me directly, and I can show you how to hook into our internal generator, so that you can generate additional languages.  We would then ask you to open source and maintain that client, so that all customers can take advantage of it.

I understand your frustration with our swagger 2.0 specs, and do hope we can provide better specs in the future.

**Comment by hbuckle** [comment]
@tedchamb - do you know if there any any plans to generate a golang sdk along with the c#, python and node ones?

**Comment by tedchamb** [comment]
@hbuckle There are no concrete plans, but we have been discussing it.
