### ISSUE TITLE
PAT authentication method

### ISSUE THREAD

**Issue by arcotek-ltd** [MicrosoftDocs/vsts-rest-api-specs#26]
Although your `curl` example uses PAT, which authentication method listed here, does PAT fall under. I suggest you either add it to the table in its own right, or if one of the items in the table already includes PAT, add it to a column titled 'e.g'. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: 34a63078-bfe5-7cb5-e278-bf9edaa3fa4d
* Content: [Get started with the REST APIs for Visual Studio Team Services and Team Foundation Server - Visual Studio Team Services REST API](https://docs.microsoft.com/en-us/rest/api/vsts/#authenticate)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Service: **unspecified**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by justmarks** [comment]
PAT is not the suggested mechanism for any of the above scenarios, which is why it's not on the list.  The primary purpose for using PAT is for access to Git.  With that said, some of our examples use it because it's a simple mechanism to show as a sample, it doesn't required wrappers or external code to function.  You can see our guidance around using PAT here: https://docs.microsoft.com/en-us/vsts/integrate/get-started/authentication/pats?view=vsts
