### ISSUE TITLE
TFS Build Definition Favorites API

### ISSUE THREAD

**Issue by WowItsDoge** [MicrosoftDocs/vsts-rest-api-specs#498]
Hi,

when I like to get a list of my favorite Build Definitions, I can use this API:

```
_apis/Favorite/Favorites?artifactType=Microsoft.TeamFoundation.Build.Definition&artifactScopeType=Project&includeExtendedDetails=true
```

I got the URL by using Azure Dev Ops Server Web UI and then clicking on Dashboards, Build History Widget edit and then opening the Pipeline List. The API Request I have seen using the Edge Browser Http Requests Tab.

But I have found no documentation for this API.

How is it possible to add and remove Favorite Build Definitions with the API?

Regards,
Jan

**Comment by WowItsDoge** [comment]
Removing of Favorites maybe works with this URL, at least when the requests are made from the TFS Web UI.

```
_apis/Favorite/Favorites/
FAVORITE_ID_REPLACED?artifactType=Microsoft.TeamFoundation.Build.Definition&
artifactScopeType=Project&artifactScopeId=ARTIFACT_SCOPE_REPLACED
```

But when this URL is manually called (with Http Delete), the status code 400 is returned.
If this URL is used with Http Get, it seams a random Favorite Build Definition is returned.

**Comment by nechvatalp** [comment]
Hello,

you have a correct API for deletion, the reason it returns 400 is because you are missing API version. You can add that either with **accept** http header or just by adding &api-version=YOUR_API_VERSION at the end of the request. You can check the accept header for the request in your web browser to check what version to use.

As for adding favorite you can use POST request on the same endpoint again I would recommend to check the request to get the idea what should be inside the POST body and the api version will also have to be specified.
